apiVersion: v1
kind: Service
metadata:
  name: commandservice-nodeport
spec:
  selector:
    app: commandservice
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the service
      targetPort: 5001   # Port on the container
      nodePort: 30006    # Port on the node
  type: NodePort
