version: '3.4'

services:
  platformservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080" #Maps port 8080 in the container to port 8081 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: platformservice
