apiVersion: apps/v1
kind: Deployment
metadata:
  name: commandservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
      - name: commandservice
        image: amrawniameen/commandservice:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: commandservice
spec:
  selector:
    app: commandservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP